### ISSUE TITLE
Wrong Script

### ISSUE THREAD

**Issue by DeepakShrm320** [DeepakShrm320/Test-Project-1#1]
do this immediately

**Comment by sajansharmaok** [comment]
dan wht 2 do???

**Comment by DeepakShrm320** [comment]
`$(document).ready(function(){
$("#submit").click(function(){
var name = $("#name").val();
var email = $("#email").val();
var password = $("#password").val();
var contact = $("#contact").val();
// Returns successful data submission message when the entered information is stored in database.
var dataString = 'name1='+ name + '&email1='+ email + '&password1='+ password + '&contact1='+ contact;
if(name==''||email==''||password==''||contact=='')
{
alert("Please Fill All Fields");
}
else
{
// AJAX Code To Submit Form.
$.ajax({
type: "POST",
url: "ajaxsubmit.php",
data: dataString,
cache: false,
success: function(result){
alert(result);
}
});
}
return false;
});
});`

**Comment by DeepakShrm320** [comment]
`


`

**Comment by sajansharmaok** [comment]
ok
